// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh6o6aqPvsjYArIXFVVgQgj8ElXKEhTSU',
    appId: '1:772377488112:android:1878a67b4551e77d9d7035',
    messagingSenderId: '772377488112',
    projectId: 'yam-foods',
    storageBucket: 'yam-foods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mKRfjFyHR1uOdmoc8h71Xnn8vyAgCFc',
    appId: '1:772377488112:ios:e3e8c6628246fd069d7035',
    messagingSenderId: '772377488112',
    projectId: 'yam-foods',
    storageBucket: 'yam-foods.firebasestorage.app',
    androidClientId: '772377488112-1dv4tiate9u7kb8817q3n4ume6ca29bt.apps.googleusercontent.com',
    iosClientId: '772377488112-62s6tau2ms95j5e9bmdcol7mr7h7oi1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.yamfoodsCustomerApp',
  );

}